using UnityEngine;

namespace GF
{
    internal enum EInputMap
    {
        NO_MAPPING,
        JOYSTICK_1_UP = KeyCode.U,
        JOYSTICK_1_DOWN = KeyCode.H,
        JOYSTICK_1_LEFT = KeyCode.G,
        JOYSTICK_1_RIGHT = KeyCode.J,
        JOYSTICK_1_BUTTON_UP = KeyCode.L,
        JOYSTICK_1_BUTTON_DOWN = KeyCode.K,
        JOYSTICK_2_UP = KeyCode.Q,
        JOYSTICK_2_DOWN = KeyCode.W,
        JOYSTICK_2_LEFT = KeyCode.R,
        JOYSTICK_2_RIGHT = KeyCode.E,
        JOYSTICK_2_BUTTON_UP = KeyCode.T,
        JOYSTICK_2_BUTTON_DOWN = KeyCode.Y,
        JOYSTICK_3_UP = KeyCode.B,
        JOYSTICK_3_DOWN = KeyCode.Alpha7,
        JOYSTICK_3_LEFT = KeyCode.N,
        JOYSTICK_3_RIGHT = KeyCode.Keypad0,
        JOYSTICK_3_BUTTON_UP = KeyCode.Keypad1,
        JOYSTICK_3_BUTTON_DOWN = KeyCode.Keypad2,
        JOYSTICK_4_UP = KeyCode.A,
        JOYSTICK_4_DOWN = KeyCode.S,
        JOYSTICK_4_LEFT = KeyCode.D,
        JOYSTICK_4_RIGHT = KeyCode.F,
        JOYSTICK_4_BUTTON_UP = KeyCode.O,
        JOYSTICK_4_BUTTON_DOWN = KeyCode.P,
        CENTRAL_BUTTON = KeyCode.I,
        DOWN_ARROW_LEFT = KeyCode.Alpha0,
        DOWNBUTTON = KeyCode.Alpha1,
        DOWN_ARROW_RIGHT = KeyCode.Alpha2,
        UP_PANNEL_LEFT_YELLOW = KeyCode.C,
        UP_PANNEL_LEFT_RED = KeyCode.Z,
        UP_PANNEL_LEFT_GREEN = KeyCode.X,
        UP_PANNEL_LEFT_BLUE = KeyCode.V,
        UP_PANNEL_WHITE_BUTTON_1 = KeyCode.Keypad4,
        UP_PANNEL_WHITE_BUTTON_2 = KeyCode.Keypad5,
        UP_PANNEL_WHITE_BUTTON_3 = KeyCode.Keypad8,
        UP_PANNEL_WHITE_BUTTON_4 = KeyCode.Keypad6,
        UP_PANNEL_WHITE_BUTTON_5 = KeyCode.Keypad3,
        UP_PANNEL_WHITE_BUTTON_6 = KeyCode.Keypad7,
        UP_PANNEL_RIGHT_RED = KeyCode.Keypad9,
        UP_PANNEL_RIGHT_BLUE = KeyCode.Space,
    }
}